---
output: 
  pdf_document:
    latex_engine: xelatex

geometry: margin=1.9cm 
mainfont: NanumGothic # Lucida Grande for Mac, Calibri for Windows, Use Ubuntu as mainfont if on Ubuntu-based linux, same idea for Mac

params:
  gender: "Male"

header-includes:
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	error = FALSE
)
```


```{r child = here::here("R/rmarkdown/front_page.Rmd")}
```

\newpage

```{r child = here::here("R/rmarkdown/bmi_report.Rmd")}
```

\newpage


```{r child = here::here("R/rmarkdown/back.Rmd")}
```

